import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/NavBar";
import { ThemeProvider } from "@/components/dashboard/ThemeProvider";
import ReactQueryClientProvider from "@/components/Provider/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog  App",
  description: "Generated by UC grp",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
   <html lang="en">
     <body className={inter.className}>
       <ReactQueryClientProvider>
         <Navbar />
         <ThemeProvider
           attribute="class"
           defaultTheme="system"
           enableSystem
           disableTransitionOnChange
         >
           {children}
         </ThemeProvider>
       </ReactQueryClientProvider>
     </body>
   </html>
 );
}
